---
- name: Setup MySQL Database and Apply Migrations
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/codespace/.python/current/bin/python3  # Specify the correct Python interpreter
  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
 
    - name: Start MySQL Service
      service:
        name: mysql
        state: started
 
    - name: Create Database
      community.mysql.mysql_db:
        name: subscribers_db
        state: present
        login_user: root
        login_password: Akhil
 
    - name: Create Subscribers Table (if not exists)
      community.mysql.mysql_query:
        login_user: root
        login_password: Akhil
        login_db: subscribers_db
        query: "CREATE TABLE IF NOT EXISTS subscribers (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), email VARCHAR(255));"
 
    - name: Setup Flyway Configuration
      become: true
      copy:
        dest: /etc/flyway.conf
        content: |
          flyway.url=jdbc:mysql://localhost:3306/subscribers_db
          flyway.user=root
          flyway.password=Akhil

    - name: Apply Migrations Using Flyway
      command: "flyway -url=jdbc:mysql://localhost:3306/subscribers_db -user=root -password=Akhil -locations=filesystem:/workspaces/Assignment4/migrations migrate"
